const commonTypes = {
  // CATEGORIES
  GET_CATEGORIES_ASYNC_START: "common/GET_CATEGORIES_ASYNC_START",
  GET_CATEGORIES_ASYNC_SUCCESS: "common/GET_CATEGORIES_ASYNC_SUCCESS",
  GET_CATEGORIES_ASYNC_FAILURE: "common/GET_CATEGORIES_ASYNC_FAILURE",

  // CATS DATA
  GET_DATA_ASYNC_START: "common/GET_DATA_ASYNC_START",
  GET_DATA_ASYNC_SUCCESS: "common/GET_DATA_ASYNC_SUCCESS",
  GET_DATA_ASYNC_FAILURE: "common/GET_DATA_ASYNC_FAILURE",
};

export default commonTypes;
